name: Checkout WF
on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -a
      - name: Checkout
        uses: action/checkout@v4
      - name: List files after
        run: ls -a
      - name: Echo vars
        run: echo "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List files after
        run: ls -a
      - name: Echo vars
        run: echo "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"