name: Status Check Functions WF
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 70 # wait for 10 secs
        timeout-minutes: 1
      - name: Fail
        id: step-2
        continue-on-error: true
        run: exit 1
      - name: Runs on step-2 Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Step 2 has failed'
      - name: Runs on Failure
        if: failure()
        run: echo 'Failure'
      - name: Runs on Success
        # this is not needed
        if: success()
        run: echo 'Runs on Success'
      - name: Runs always
        # this is not needed
        # if: success() || failure()
        if: always()
        run: echo 'Runs on Success'
      - name: Runs when cancelled
        if: cancelled()
        run: echo 'Runs on Cancel'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'